# Generated by Django 5.2.6 on 2025-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standards',
            name='names',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
